user: joceran
group: benchmark_test
description: "This benchmark is for testing benchmark."

system:
  name: hp_pavillon
  type: laptop

parameters:
  num_workers: 6
  evaluator_method: process
  max_evals: 10
  starting_point: [-32.768, 32.768]