script: local/hps_ambs_auto_sklearn.py
database: db.json

summary:
  user: joceran
  group: surrogate_models
  label: Random Forest
  description:

env:
  system:
    name: hp_pavillon
    type: laptop

parameters:
  surrogate_model: GBRT
  max_evals: 50