script: local/hps_ambs_auto_sklearn.py
database: db.json

summary:
  user: joceran
  group: hps_ambs_autosklearn
  label: default
  description:

env:
  system:
    name: hp_pavillon
    type: laptop

parameters:
  max_evals: 70
  num_workers : 1