script: local/hps_101.py
database: db2.json

summary:
  user: joceran
  group: evaluator_test
  label: process
  description: This benchmark is for testing benchmark.

env:
  system:
    name: hp_pavillon
    type: laptop

parameters:
  evaluator_method: process