title = "CBBO Benchmark"

[search]
max_evals = 500
num_replications = 10

[search.method.cbo]
package = "deephyper.hpo"
name = "CBO"
kwargs.acq_optimizer = "ga"

[search.method.random]
package = "deephyper.hpo"
name = "RandomSearch"

[search.method.tpe]
package = "deephyper_benchmark.hpo.optuna"
name = "OptunaSearch"
kwargs.sampler = "TPE"

[search.method.cmaes]
package = "deephyper_benchmark.hpo.optuna"
name = "OptunaSearch"
kwargs.sampler = "CMAES"

[evaluator]
method = "thread"
num_workers = 1

# [benchmark.ackley]
# package = "deephyper_benchmark.benchmarks.cbbo"
# name = "AckleyBenchmark"

[benchmark.branin]
package = "deephyper_benchmark.benchmarks.cbbo"
name = "BraninBenchmark"
